# Generated by Django 5.2.8 on 2025-11-22 18:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('polls', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='question',
            name='description',
            field=models.CharField(max_length=1500, null=True, verbose_name='Полное описание'),
        ),
        migrations.AlterField(
            model_name='question',
            name='image',
            field=models.ImageField(blank=True, upload_to='polls/questions', verbose_name='Изображение'),
        ),
        migrations.AlterField(
            model_name='question',
            name='pub_date',
            field=models.DateTimeField(verbose_name='Дата публикации'),
        ),
        migrations.AlterField(
            model_name='question',
            name='short_description',
            field=models.CharField(max_length=450, null=True, verbose_name='Краткое описание'),
        ),
    ]
